version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - restore_cache:
          keys:
            - poetry-v1-{{ checksum "poetry.lock" }}
            - poetry-v1-

      - run:
          name: Install Poetry
          command: |
            python -m pip install --upgrade pip
            pip install poetry

      - run:
          name: Configure Poetry
          command: |
            poetry config virtualenvs.create true
            poetry config virtualenvs.in-project true

      - run:
          name: Install dependencies
          command: |
            poetry install

      - save_cache:
          paths:
            - .venv
          key: poetry-v1-{{ checksum "poetry.lock" }}

      - run:
          name: Run Ruff
          command: |
            poetry run ruff format --check .
            poetry run ruff check .

      - run:
          name: Run tests
          command: |
            poetry run pytest

workflows:
  test:
    jobs:
      - test